/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programming.task1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TableTest {
    @Test void appAddSign() {
        Table table = new Table(3,3);
        table.addSign(3,3, Table.Sign.SIGN_X);
        table.addSign(2,2,Table.Sign.SIGN_ZERO);
        assertEquals(Table.Sign.SIGN_X, table.getSign(3,3));
        assertEquals(Table.Sign.SIGN_ZERO, table.getSign(2,2));
        assertNotEquals(Table.Sign.SIGN_X, table.getSign(2,2));
    }

    @Test void appClear() {
        Table table = new Table(3,3);
        table.addSign(1,1,Table.Sign.SIGN_X);
        table.addSign(3,3,Table.Sign.SIGN_ZERO);
        table.addSign(3,3,Table.Sign.SIGN_EMPTY);
        assertEquals(Table.Sign.SIGN_EMPTY, table.getSign(3,3));
        assertEquals(Table.Sign.SIGN_EMPTY, table.getSign(2,2));
        assertNotEquals(Table.Sign.SIGN_EMPTY, table.getSign(1,1));
    }

    @Test void appMaxLength() {
       Table table = new Table(3,3);
       table.addSign(1,1,Table.Sign.SIGN_X);
       table.addSign(1,2,Table.Sign.SIGN_X);
       table.addSign(1,3,Table.Sign.SIGN_ZERO);
       table.addSign(3,3,Table.Sign.SIGN_X);
       table.addSign(2,2,Table.Sign.SIGN_ZERO);
       table.addSign(3,1,Table.Sign.SIGN_ZERO);
       System.out.println(table.toString());
       assertEquals(2,table.maxLength(Table.Sign.SIGN_X));
       assertEquals(3,table.maxLength(Table.Sign.SIGN_ZERO));
        table.addSign(2,2,Table.Sign.SIGN_EMPTY);
        System.out.println(table.toString());
       assertEquals(1,table.maxLength(Table.Sign.SIGN_ZERO));
        table.addSign(2,2,Table.Sign.SIGN_X);
        table.addSign(3,2,Table.Sign.SIGN_X);
        table.addSign(3,3,Table.Sign.SIGN_EMPTY);
        System.out.println(table.toString());
       assertEquals(3,table.maxLength(Table.Sign.SIGN_X));
    }
}
