/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programming.task1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TicTacToeTest {
    @Test void appAddZero() {
        TicTacToe field = new TicTacToe(3);
        field.addZero(2, 2);
        field.addZero(1,1);
        field.addCross(3,3);
        assertEquals("0",field.getValue(1, 1));
        assertEquals("0",field.getValue(2, 2));
        assertNotEquals("0",field.getValue(3, 3));
    }

    @Test void appAddCross() {
        TicTacToe field = new TicTacToe(3);
        field.addCross(2, 2);
        field.addCross(1,1);
        field.addZero(3,3);
        assertEquals("X",field.getValue(1, 1));
        assertEquals("X",field.getValue(2, 2));
        assertNotEquals("X",field.getValue(3, 3));
    }

    @Test void appClear() {
        TicTacToe field = new TicTacToe(3);
        field.addZero(2, 2);
        field.addZero(1,1);
        field.addCross(3,3);
        field.clear(3, 3);
        assertEquals("0",field.getValue(1, 1));
        assertEquals("*",field.getValue(1, 2));
        assertEquals("*",field.getValue(3, 3));
    }

    @Test void appMaxSequence() {
        TicTacToe field = new TicTacToe(3);
        field.addZero(2, 2);
        field.addZero(1,1);
        field.addZero(3,3);
        field.addCross(1, 2);
        field.addCross(1, 3);
        field.addZero(2, 1);
        field.addCross(2, 3);
        assertEquals(2, field.maxSequence("X"));
        assertEquals(3, field.maxSequence("0"));
    }
}
