/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programming.task1;

import java.util.*;



public class AddressBook {

    private final Map<String, Address> addresses = new LinkedHashMap<>();

   public boolean addPerson(String name, Address address) {
       if (addresses.containsKey(name)) return false;
       addresses.put(name, address);
       return true;
   }

    public boolean deletePerson(String name) {
        if (!addresses.containsKey(name)) return false;
        addresses.remove(name);
        return true;
    }

    public boolean changeAddress(String name, Address newAddress) {
        if (!addresses.containsKey(name)) return false;
        addresses.replace(name, addresses.get(name), newAddress);
        return true;
    }

    public Address getAddressByName(String name) {
        if (addresses.containsKey(name)) return addresses.get(name);
        return null;
    }

    public List<String> getNamesByStreet(Address address) {
        List<String> names = new ArrayList<>();
        for (String key : addresses.keySet()) {
            if (addresses.get(key).getStreet().equals(address.getStreet())) names.add(key);
        }
        return names;
    }

    public List<String> getNamesByHome(Address address) {
        List<String> names = new ArrayList<>();
        for (String key : addresses.keySet()) {
            if (addresses.get(key).getStreet().equals(address.getStreet()) && addresses.get(key).getHome() == address.getHome()) names.add(key);
        }
        return names;
    }
}

class Address {

    private String street;
    private int home;
    private int flat;

    public Address(String street, int home, int flat) {
        this.street = street;
        this.home = home;
        this.flat = flat;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public int getHome() {
        return home;
    }

    public void setHome(int home) {
        this.home = home;
    }

    public int getFlat() {
        return flat;
    }

    public void setFlat(int flat) {
        this.flat = flat;
    }
}

