/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programming.task1;

import java.util.HashMap;
import java.util.Map;

public class PriceList {
    private final Map<Integer, ProductDetails> priceList = new HashMap<>();

    public boolean addProduct(int code, ProductDetails product) {
        if (priceList.containsKey(code)) return false;
        priceList.put(code, product);
        return true;
    }

    public boolean replacePrice (int code, Double newPrice) {
        if (!priceList.containsKey(code)) return false;
        priceList.replace(code, new ProductDetails(priceList.get(code).getName(), newPrice));
        return true;
    }

    public boolean replaceName (int code, String newName) {
        if (!priceList.containsKey(code)) return false;
        priceList.replace(code, new ProductDetails(newName, priceList.get(code).getPrice()));
        return true;
    }

    public boolean deleteProduct (int code) {
        if (!priceList.containsKey(code)) return false;
        priceList.remove(code);
        return true;
    }

    public Double findCost(int code, int quantity) {
        return priceList.get(code).getPrice() * quantity;
    }

    public ProductDetails getValue (int code) {
        return priceList.get(code);
    }
}

class ProductDetails {
    private final String name;
    private final Double price;

    public ProductDetails(String name, Double price) {
        this.name = name;
        this.price = price;
    }

    public String getName() {
        return name;
    }

    public Double getPrice() {
        return price;
    }
}
