/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programming.task1;

import java.security.SignatureException;

public final class TicTacToe {

    private final int size;

    private final String[][] field;

    public enum Value{
        CROSS("X"), ZERO("0"), EMPTY("*");
        private final String value;
        Value(String value) {
            this.value = value;
        }
    }

    public TicTacToe(int size) {
        this.size = size;
        field = new String[size][size];
        for (int i = 0; i < size; i++)
            for(int j = 0; j < size; j++) {
                field[i][j] = Value.EMPTY.value;
            }
    }

    //добавление нолика
    public void addZero(int row, int column) {
        if (field[row - 1][column - 1].equals(Value.EMPTY.value)) field[row - 1][column - 1] = Value.ZERO.value;
    }

    //добавление крестика
    public void addCross(int row, int column) {
        if (field[row - 1][column - 1].equals(Value.EMPTY.value)) field[row - 1][column - 1] = Value.CROSS.value;
    }

    //получение значения поля(для тестов)
    public String getValue(int row, int column) {
        return field[row - 1][column - 1];
    }

    //очистка поля
    public void clear(int row, int column) {
        if (!field[row - 1][column - 1].equals(Value.EMPTY.value)) field[row - 1][column - 1] = Value.EMPTY.value;
    }

    //поиск максимальной последовательности
    public int maxSequence(Value sign) {
        int maxLength = -1;
        int length = 0;
        //главная диагональ
        for (int i = 0; i < size; i++) {
            if (field[i][i].equals(sign.value)) length++;
                    else length = 0;
            if (maxLength < length) maxLength = length;
        }

        //побочная диагональ
        length = 0;
        for (int i = 0; i < size; i++) {
            if (field[i][size - i - 1].equals(sign.value)) length++;
                    else length = 0;
            if (maxLength < length) maxLength = length;
        }

        //вертикаль
        for (int j = 0; j < size; j++) {
            length = 0;
            for (int i = 0; i < size; i++) {
                if (field[i][j].equals(sign.value)) length++;
                        else length = 0;
                if (maxLength < length) maxLength = length;
            }
        }

        //горизонталь
        for (int i = 0; i < size; i++) {
            length = 0;
            for (int j = 0; j < size; j++) {
                if (field[i][j].equals(sign.value)) length++;
                        else length = 0;
                if (maxLength < length) maxLength = length;
            }
        }
        return maxLength;
    }
}
